import Head from 'next/head'
import { Inter } from '@next/font/google'
import { login, signUp } from 'src/firebase/firebase'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CO-DENAITO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => signUp('poko@gmail.com', 'tojo123')}>
        ユーザー登録
      </button>
      <button onClick={() => login('poko@gmail.com', 'tojo123')}>
        ユーザーログイン
      </button>
    </>
  )
}
