/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import { login, signUp } from 'src/firebase/firebase'
import { TextInput } from 'src/components/TextInput'
import { useState } from 'react'
import { Button } from 'src/components/Button/Index'
import Login from 'src/pages/login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CO-DENAITO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </>
  )
}
